name: k6 Load Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test and save JSON
        run: k6 run --out json=test-results.json test.js

      - name: Upload k6 results artifact
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: test-results.json
