name: k6 Load Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 for all test files and save results
        run: |
                for f in $(find . -type f -name "*.js"); do
                  OUT="$(echo "$f" | sed 's#^\./##; s#/#_#g; s#\.js$#-results.csv#')"
                  echo "Running k6 for $f, saving results to $OUT"
                  k6 run --out csv="$OUT" "$f"
                done

      - name: Upload all k6 CSV result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: "*.csv"
