name: k6 Load Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 for all test files and save results
        run: |
          for f in test*.js; do
            OUT="${f%.js}-results.json"
            k6 run --out json="$OUT" "$f"
          done

      - name: Upload all k6 result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: "*.json"
