name: k6 Load Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test and save JSON
        run: k6 run --out json=test-results.json test.js
        uses: grafana/run-k6-action@v1
        with:
          path: test.js  # Path to your k6 script
